### ISSUE TITLE
Issue with second question

### ISSUE THREAD

**Issue by callRoko** [learn-co-curriculum/conditionals-python-lab#3]
I wrote the code for the second question asking about the cheaper restaurant and this is what I am getting
restaurant = frontier_restaurant
alternative = fork_fig
def cheaper_restaurant(restaurant, alternative):
    if len(restaurant['price']) < len(alternative['price']):
        return restaurant['name']
    if len(restaurant['price']) > len(alternative['price']):
        return alternative['name']
    return "Restaurant prices are the same"
print(cheaper_restaurant(fork_fig, frontier_restaurant)['name']) # 'Frontier Restaurant'
print(cheaper_restaurant(frontier_restaurant, fork_fig)['name']) # 'Frontier Restaurant'
TypeErrorTraceback (most recent call last)
<ipython-input-36-f633e17b0823> in <module>()
----> 1 print(cheaper_restaurant(fork_fig, frontier_restaurant)['name']) # 'Frontier Restaurant'
      2 print(cheaper_restaurant(frontier_restaurant, fork_fig)['name']) # 'Frontier Restaurant'

TypeError: string indices must be integers

**Comment by mas16** [comment]
Hi callRoko, thanks for flagging. The solution has been updated.
