### ISSUE TITLE
Conditionals in python lab

### ISSUE THREAD

**Issue by doghigh** [learn-co-curriculum/conditionals-python-lab#4]
The "cheaper_restaurant" code in the solution and the code in the test of the code have errors. 
the solution code:
  `  def cheaper_restaurant(restaurant, alternative):
        if len(restaurant['price']) < len(alternative['price']):
            return restaurant
        if len(restaurant['price']) > len(alternative['price']):
           return alternative
        return "Restaurants are the same price!" `
    `print(cheaper_restaurant(fork_fig, frontier_restaurant)['name']) # 'Frontier Restaurant'`
   ` print(cheaper_restaurant(frontier_restaurant, fork_fig)['name']) # 'Frontier Restaurant'`
    Frontier Restaurant
    Frontier Restaurant
![image](https://user-images.githubusercontent.com/22271083/61212279-a5f3fc80-a6b6-11e9-9975-617d61c8883f.png)

1. adding "len" doesn't do anything for the code
2. The lines to print out which restaurant is cheaper sends an error if the prices are the same.
3. The code is more robust if "cheaper_restaurant" was returned all three times.
4. My solution:
   ` def cheaper_restaurant(restaurant, alternative):
        if restaurant['price'] < alternative['price']:
            cheaper_restaurant = restaurant['name']
        elif restaurant['price'] > alternative['price']:
              cheaper_restaurant = alternative['name']
        elif restaurant['price'] == alternative['price']:
            cheaper_restaurant = "Restaurants are the same!"
    return cheaper_restaurant
`
   ` print(cheaper_restaurant(fork_fig, frontier_restaurant)) `
   ` print(cheaper_restaurant(frontier_restaurant, fork_fig)) `
Results:
if fork_fig < frontier_restaurant:
![image](https://user-images.githubusercontent.com/22271083/61212030-ed2dbd80-a6b5-11e9-9d2e-451479420473.png)
if frontier < fork
![image](https://user-images.githubusercontent.com/22271083/61212098-1e0df280-a6b6-11e9-94e7-a4d9a48ba513.png)
if frontier == fork
![image](https://user-images.githubusercontent.com/22271083/61212162-4564bf80-a6b6-11e9-930d-e74fc5278c47.png)

**Comment by mas16** [comment]
Hi catsjc1175, thank you for pointing this out. The function has been updated to eliminate the error.
